# fly.toml file generated for focus-pods on 2022-11-16T16:55:14+01:00

app = "focus-pods"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  APP_ENV = "production"
  DB_CONNECTION = "pgsql"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
